# Generated by Django 3.0 on 2020-03-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(default='', max_length=50, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='segment',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='段别'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='work_num',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='工号'),
        ),
    ]
