# Generated by Django 3.0 on 2020-03-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20200312_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='project',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='专案'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='备注'),
        ),
    ]
