# Generated by Django 3.0 on 2020-04-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_process', '0001_initial'),

    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='publish_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='withdraw_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='接收时间'),
        ),
    ]
